name: Build LaTeX

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full latexmk

      - name: Build PDF
        run: |
          mkdir -p out
          latexmk -pdf -interaction=nonstopmode -output-directory=out main.tex

      - name: Show workspace contents
        run: ls -R .

      - name: Upload PDF as artifact
        # Zum Test auf v2 pinnen – später wieder auf v3 umstellen
        uses: actions/upload-artifact@v2
        with:
          name: PDF-Dokument
          path: out/main.pdf
