name: Build & Publish PDF

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug list workspace
        run: |
          echo "Working directory: $PWD"
          ls -R $PWD

      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full latexmk

      - name: Build PDF
        run: |
          mkdir -p out
          latexmk -xelatex -interaction=nonstopmode -output-directory=out doc/main.tex

      - name: Prepare docs folder
        run: |
          mkdir -p docs
          cp out/main.pdf docs/main.pdf

      - name: Commit and push PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/main.pdf
          git commit -m "Automated PDF build [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
