name: Test Artifact Upload

on: [push]

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create test file
        run: |
          mkdir -p test-out
          echo "Hallo Test" > test-out/test.txt

      - name: Show workspace (Debug)
        run: ls -R .

      - name: Upload test artifact
        uses: actions/upload-artifact@v3
        with:
          name: test_artifact
          path: test-out/test.txt
